//server ns1

zone "netflix.ar" {
    type master;
    file "/etc/bind/db.netflix";
    allow-query {any;}; 
    allow-transfer {slaves;}; 
};

zone "147.13.200.in-addr.arpa" {
    type master;
    file "/etc/bind/rev.netflix";
};

//server ns2

zone "netflix.ar" {
    type slave;
    masters {200.13.147.60;};
    file "/etc/bind/db.netflix";
};

// db.netflix de ns1

$ TTL 1d
$ ORIGIN netflix.ar.

@ IN SOA ns1.netflix.ar. hostmaster.netflix.ar. (2020111801; serial
                                                         5h; refresh
                                                        15m; update retry
                                                        3W12h; expiry
                                                        2h20m; TTL negativo)
                        IN NS ns1.netflix.ar.
                        IN NS ns2.lucifer.netflix.ar.
                        IN MX 10 mx.netflix.ar.
                        IN MX 20 mx.lucifer.netflix.ar.

www                     IN A 200.13.147.60
ns1                     IN CNAME www
ns2.lucifer             IN A 200.13.147.90
mx                      IN A 200.13.147.59
mx.lucifer              IN A 200.13.147.113

// db.netflix de ns2

$ TTL 1d
$ ORIGIN netflix.ar.

@ IN SOA ns1.netflix.ar. mx.netflix.ar. (2020111801; serial
                                                 5h; refresh
                                                15m; update retry
                                                3W12h; expiry
                                                2h20m; TTL negativo)
                        IN NS ns1.netflix.ar.
                        IN NS ns2.lucifer.netflix.ar.
                        IN MX 10 mx.netflix.ar.
                        IN MX 20 mx.lucifer.netflix.ar.

www                     IN A 200.13.147.60
ns1                     IN CNAME www
ns2.lucifer             IN A 200.13.147.90
mx                      IN A 200.13.147.59
mx.lucifer              IN A 200.13.147.113





// rev.netflix de ns1

$ TTL 1d
$ ORIGIN 147.13.200.IN-ADDR.ARPA. 

@ IN SOA ns1.netflix.ar. mx.netflix.ar. (2020111801; serial
                                                 5h; refresh
                                                15m; update retry
                                                3W12h; expiry
                                                2h20m; TTL negativo)
                        IN NS ns1.netflix.ar.

60                      IN PTR ns1.netflix.ar.
90                      IN PTR ns2.lucifer.netflix.ar.
59                      IN PTR mx.netflix.ar.
113                     IN PTR mx.lucifer.netflix.ar.
60                      IN PTR www.netflix.ar.