zone "cargill.com"{
    type "master"
    file "/etc/bind/cargill.db"
}
zone "229.3.in-addr.arpa"{
    type "master"
    file "/etc/bind/cargill.rev"
}
zone "cargillargentina.com.ar"{
    type "slave"
    masters {52.207.108.232}
    file "/etc/bind/cargillargentina.db"
}